### PR TITLE
Update test suite

### PR DESCRIPTION
**Pull request by mosesyhc**
This PR aims to improve test coverages, update maintained code, and remove unused or incorrect code.

- [x] Tackle #29 
- [ ] Include bookending tests for package versions (https://github.com/bandframework/surmise/issues/74#issuecomment-2187329814)

### Source files with under 95% coverage (checkmarks indicate acceptable behavior)
- [ ] surmise\calibration.py	58% --> 75%
- [x] surmise\calibrationmethods\directbayes.py	72% --> 84%
- [x] `surmise\__init__.py`	83%
- [x] surmise\emulation.py	85% --> 87%
- [x] surmise\utilities.py	92%
- [x] surmise\emulationmethods\PCGPwM.py	93%
- [x] surmise\utilitiesmethods\metropolis_hastings.py	93%

### Test files with under 100% coverage
- [ ] tests\test_new_calibrator\test_new_cal.py	43%
- [ ] tests\test_new_emulator\test_new_emu.py	43%
- [ ] tests\test_new_emulator\test_new_emu_prediction.py	65%
- [x] tests\test_emu_cal\test_emu_passfunc.py	87% --> 97%
- [x] tests\test_emu_cal\test_emu_x1d.py	91% --> 100%
- [x] tests\test_emu_cal\test_cal_directbayeswoodbury.py	95% --> 100%
- [x] tests\test_emu_cal\test_emu_update.py	95%
- [x] tests\test_emu_cal\test_emu_init.py	97% --> 100%
- [x] tests\test_emu_cal\test_emu_predict.py	97% --> 100%
- [x] tests\test_emu_cal\test_cal_mh.py	98%
- [x] tests\test_emu_cal\test_emu_remove.py	98% --> 100%
- [x] tests\test_emu_cal\test_emu_pcgpwm.py	99% --> 100%

### CODE REVIEW

**Comment by mosesyhc** [comment]
#120 contains the commit history relevant to this branch (prior to PR/merge mess-up)

**Comment by jared321** [comment]
@mosesyhc has finished his review.  I reviewed my changed files, but those will be updated soon on a new branch.

**Comment by jared321** [comment]
I am performing this merge locally so that I can study the result and understand how we got it before I push.

My understanding based on looking at the local merge result with GitKraken:
* The current commit on `v0.3-update` is 35101ae0a10948f3db473a6faffa993dccab3e7a
* Due to a series of merges/reverts that current commit is identical to an early commit that cleaned up sphinx docs and that contains all the changes from PR #118 (c0f0d8accf47d467d2c6d3187b1af0d532363e08)
* After c0f0d8accf47d467d2c6d3187b1af0d532363e08, `update_test_suite` was accidentally merged in and some minor changes were made to placate flake8 (b104e4077682ac08fd562c6f8a55e2adc5a034f5)
* That commit was then merged into `update_test_suite` at commit 0a645bf486c168a1a9641af44abec4b672d32701
* There was some more merge/revert work and the commit a7f3e0be99592228eb1b863b0593573433f15163 on `update_test_suite` is identical to commit 0a645bf486c168a1a9641af44abec4b672d32701.  This means that
  * The PR #118 work, the sphinx changes, and the flake8 changes all made it into `update_test_suite` at this point
* Three commits were then made to `update_test_suite`, but did not yet make it onto `v0.3-update`
* When `v0.3-update` was merged into `update_test_suite` via the GH interface to address the PR merge conflict on `python-package.yaml` that was blocking actions, it overwrote everything on `update_test_suite` except for the changes of the last three commits (diff merge with last effective commit on `v0.3-update` c0f0d8accf47d467d2c6d3187b1af0d532363e08).  Poking around we can conclude the following for the four files altered on the last three commits.
  * `python_package.yml` - no significant change after revert
  * `run_full_test_suite.sh` - not affected by revert and correct after merge
  * `conftest.py` - not affected by revert and change present after merge
  * `emulation.py` - involved in revert, but change present after merge

**Comment by mosesyhc** [comment]
@jared321: This is incredible (detective) work. Thank you for tracing our steps and helping with understanding the GH merge and conflict resolution behavior.

**Pull request merged**
