### PR TITLE
Tox integration & use in GitHub actions

### PR DESCRIPTION
**Pull request by jared321**
The work associated with Issue #106 appears to be finished.  The following are the steps I will carry out as part of a self-review of this PR

- [x] Full review of all changes made to the code
- [x] Run all tox tasks locally and check products
- [x] Add bad style to file and see tox and CI action fail as expected
- [x] Break code and see nocoverage/coverage fail in tox and in all CI actions as expected
- [x] Breaks docs so that a warning is issued.  Confirm warning treated as error with tox and CI actions as expected.
- [x] Breaks docs so that an error is issued.  Confirm error with tox and CI actions as expected.
- [x] Alter code so that coverage changes.  Check for changes in local tox report and Coveralls.
- [x] Download HTML and PDF docs and sanity check contents.  Review tox section carefully.
- [x] Download coverage reports and sanity check
- [x] Read through all action logs for correctness

I injected many different errors into the sphinx documentation including using `tx.rst` instead of `tox.rst` when including the latter and writing `:mah:` instead of `:math:`.  In such cases, `sphinx-build` reports these as errors in its output but returns a zero exit code, which indicates success.  I saw this when running `sphinx-build` from the command line and tox reports success.  When I use the flag `--fail-on-warning` with `sphinx-build`, the output states that these are warnings that are being treated as errors and a nonzero exit code is emitted.  It appears that `sphinx-build` does not have errors or handle these in normal ways.  Therefore, I would never use `sphinx-build` in automated processes without that flag.

Note that this work has also instituted the necessary changes so that Python 3.8 is no longer a supported version.  See Issue #112.  All tests are passing with 3.12 for Windows, Ubuntu, and macOS.  I updated all actions that use a single Python version to use 3.12 except for building sphinx document, which reported an error associated with loading sphinxcontrib.bibtex.

I have changed the RTD setup so that build warnings are treated as errors.  We need to check that manually once this branch is in main.

@mosesyhc I have finished my review and have added you as a reviewer.  Some potentially useful information for you:
* When I run the test suite locally, I get three warnings about transposing `f`.  However, some CI testing actions report (e.g. macOS 3.11) the following as well
```
tests/test_emu_cal/test_cal_mh.py::test_cal_MLcal[input13-input23-expectation3]
  /home/runner/work/surmise/surmise/surmise/utilitiesmethods/metropolis_hastings.py:80: RuntimeWarning: overflow encountered in exp
    p_accept = min(1, np.exp(logpost - lposterior[i-1]))
```
* Also, the Windows testing actions logs do not suggest that the test suite was actually run.  In particular, there is no standard output logging from your testing script.

### CODE REVIEW

**Comment by jared321** [comment]
@mosesyhc The repo currently specifies dependencies in `pyproject.toml` and `requirements.txt`.  Can we get rid of the latter?

**Comment by mosesyhc** [comment]
> @mosesyhc The repo currently specifies dependencies in `pyproject.toml` and `requirements.txt`. Can we get rid of the latter?

Yes, we can.

**Comment by jared321** [comment]
@mosesyhc Your main README file presently includes all requirements including version info, which is a maintenance issue.  For instance, we forgot to update it to reflect that you can now use only >= 3.9.  It might be a good idea to update the README so that it doesn’t specify such details.  We could, for instance, refer readers who are interested in dependency fine details to pyproject.toml .

Since you have your docs available in RTD and you include a link to it, do you really need to include in the README information about how to build the docs from scratch?  If you suspect that few people would need to build the docs locally, we could just add a link to the tox info in the RTD docs.  This would potentially make the README simpler for the general user and for maintenance.  Also, we could remove the current makefile, which has been effectively replaced by tox for tox users and CI actions.

**Review by mosesyhc — APPROVED** [review]
I reviewed by performing these tasks:

- I have installed tox locally following tox instruction.
- I ran the tox commands and verified the usages.
  - `tox -e check` is scanning every directory under `surmise`, including local builds and IDE-generated venvs.  I am including these into .flake8 ignores.

All look fine to me otherwise.

**Pull request merged**
