### PR TITLE
Create publish.yml

### PR DESCRIPTION
**Pull request by mosesyhc**

### CODE REVIEW

**Comment by wildsm** [comment]
This looks neat but I am scared to test it :)

**Comment by wildsm** [comment]
Has the associated repository secret referenced in the yml been setup @mosesyhc ?

**Comment by mosesyhc** [comment]
@wildsm : Great question.. I never had to explicitly set it up..

I believe PyPI accepts publishing only via surmising and fetches the secret key there? I will have to look..

**Comment by mosesyhc** [comment]
@wildsm : No I was wrong.  We need to set the secret key up from PyPI end.

https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by wildsm** [comment]
I suggest postponing this until everything else is set for v2. Then this can be a final PR to main.

**Comment by mosesyhc** [comment]
Adding a note here: this action only publishes a package marked for release. Once we finalize which commit the tag is on, then we can release v0.2.0.  That push / pull_request should trigger a publish.

**Comment by mosesyhc** [comment]
The sequence of actions to set up PyPI for surmise: (tested with https://github.com/mosesyhc/LCGP/releases/tag/v0.1.2)

1. In pypi, under surmise's publishing tab, add a new publisher:
  - Owner: bandframework
  - Repository name: surmise
  - Workflow name: publish.yml _or workflow with other name, stored under .github/workflows/_
  - Environment name: _left empty to allow release by tags_
2. Assign tag v0.2.0, or update tag to desired commit.
3. On Github, publish a new release with tag v0.2.0.
4. The workflow will be triggered by (3) and publish to PyPI.

**Review by ozgesurer — APPROVED** [review]

**Pull request merged**
